emit:
  - "@typespec/openapi3"
  - "@kattebak/typespec-zod-emitter"
  - "@kattebak/typespec-enum-emitter"
  - "@kattebak/typespec-drizzle-orm-generator"

options:
  "@typespec/openapi3":
    emitter-output-dir: "{project-root}/../build/openapi"
  "@kattebak/typespec-zod-emitter":
    emitter-output-dir: "{project-root}/../build/validators"
    package-name: "@tdpl/validators"
    package-version: "0.0.1"
  "@kattebak/typespec-enum-emitter":
    emitter-output-dir: "{project-root}/../build/enums"
    package-name: "@tdpl/enums"
    package-version: "0.0.1"
  "@kattebak/typespec-drizzle-orm-generator":
    emitter-output-dir: "{project-root}/../build/db-schema"
